# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(my_array[-1], my_array[-3], my_array[-5], my_array[-7], my_array[-9])

9 7 5 3 1


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [7]:
import numpy as np
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_array[3:7]

array([3, 4, 5, 6])

In [9]:
my_array[-2:-4]

array([], dtype=int32)

## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [ ]:
#ser'ia parecido al anterior pero con otras posiciones pero no me sale

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [10]:
my_array20 = np.arange(20).reshape((4,5))
my_array20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
my_array20.T


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [12]:
my_array20[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [ ]:
## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [15]:
my_array20 = np.arange(20).reshape((4,5))
my_array20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
my_array20[[0,0,1,2,2,3],[1,3,0,1,3,0]].reshape((2,3))

array([[ 1,  3,  5],
       [11, 13, 15]])

In [17]:
my_array20[[0,0,1],[1,3,0]]

array([1, 3, 5])

In [18]:
my_array20[[2,2,3],[1,3,0]]

array([11, 13, 15])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [27]:
my_array20[[1,0,0,0,0,2,1,1,1,1,3,2,2,2,2],[[0,4,3,2,1,0,4,3,2,1,0,4,3,2,1]].reshape((3,5))

SyntaxError: unexpected EOF while parsing (<ipython-input-27-6d0487e95e3b>, line 1)

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [14]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filter = x=="Loro"
filter
filter_arr = x[filter]
print(filter)
filter_arr

[ True False False  True False]


array(['Loro', 'Loro'], dtype='<U5')

In [13]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filter2 = []
for element in x:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element == "Loro":
    filter2.append(True)
  else:
    filter2.append(False)

filter_arr2 = x[filter2]

print(filter2)
print(filter_arr2)

[True, False, False, True, False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [19]:
my_array20 = np.arange(20).reshape(2,5,2)
my_array20

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [36]:
my_array20 = np.arange(20).reshape((4,5))
my_array20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
array1D = my_array20.reshape(1,20)
reverse1D = np.flip(array1D)
reverse1Dmas1 = 1+ reverse1D
reverse1Dmas1.reshape(4,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [29]:

reverse_my_array20 = my_array20[::-1]
reverse_my_array20

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [51]:
matriz1010 = np.zeros(10)
print(matriz1010)
memoria = matriz1010.nbytes
print(memoria)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [56]:
vector1 = np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [57]:
reversector=np.flip(vector1)
reversector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [62]:
array = [1,2,0,0,4,0]
[i for i, element in enumerate(array) if element != 0]

[0, 1, 4]

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [65]:
data = np.random.randn(10,10)
data

array([[ 1.95582999,  0.04804632, -0.07026878,  0.8638673 , -0.26349094,
        -0.67221285, -0.08532024,  1.62170323, -0.71522603,  0.59942221],
       [-0.5775492 ,  0.60429601, -0.5844372 ,  0.10661645, -0.04474921,
        -1.73903421,  0.432972  ,  1.52130475,  0.51241992, -1.98680453],
       [-1.85778019, -0.22725466, -0.17260361,  0.39462291, -0.29841749,
        -0.86336128,  1.33916369,  0.76520353, -0.43945843, -1.70022671],
       [-0.16730997, -0.4568659 , -0.00862967,  0.24089851,  0.17609513,
        -0.89678118, -1.27072309,  1.08999448,  0.15007833,  1.00305408],
       [-0.75916439, -1.19988783,  1.58654   ,  0.89949453, -1.30241927,
        -1.46136471,  0.50817382, -0.97071841,  0.91000494,  0.43299754],
       [ 0.81137901,  0.60214043,  0.49427117,  0.47173608, -0.359211  ,
         0.48288179,  0.63676168, -1.16872382, -0.00812585, -0.22333087],
       [-0.63985386,  0.45727733,  2.56996097, -1.13481006, -0.37416025,
        -0.06336127, -1.45620767, -2.479642  

In [66]:
np.amax(data)

2.5699609656792126

In [67]:
np.amin(data)

-3.389931870703173

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [68]:
vector1 = np.arange(30)
vector1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
np.average(vector1)

14.5

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [75]:
matriz_origen = np.zeros(16).reshape(4,4)
matriz_origen[0] = [1,1,1,1]
matriz_origen[3] = [1,1,1,1]
matriz_origen[:,0] = [1,1,1,1]
matriz_origen[:,3] = [1,1,1,1]
matriz_origen

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [76]:
matriz_origen = np.zeros(64).reshape(8,8)
matriz_origen

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
matriz_origen[::2,::2] = 1
matriz_origen[1::2,1::2] = 1
matriz_origen

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [80]:
a = np.array([[0,1],[1,0]])
b = np.tile(a, (4,4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [87]:
data = np.random.randn(5,5)
print(data)
avrg = np.average(data)
datamean = np.mean(data)
print(avrg)
print(datamean)
data_desv = np.std(data)
print(data_desv)
Norm_data = (data - datamean)/data_desv
print(Norm_data)

[[-1.68490904  0.3970858  -0.75735837 -0.25327598  1.67272889]
 [ 0.27963021  1.10627171  1.54868077 -0.1697485   0.41718594]
 [ 0.70275242 -0.34683395  0.09827564  0.28000529  0.89300808]
 [ 0.38262417  1.91975523 -1.15270561  0.46340866 -0.77718563]
 [-0.77794505 -0.34889689  0.02466656  0.91421722  0.2162839 ]]
0.20190885881283685
0.20190885881283685
0.8580355014091013
[[-2.19899748  0.22746954 -1.11798081 -0.53049651  1.71417153]
 [ 0.09058058  1.05399235  1.56959929 -0.43314916  0.2508953 ]
 [ 0.5837096  -0.63953392 -0.12077964  0.09101771  0.80544362]
 [ 0.21061519  2.00206911 -1.57873942  0.30476572 -1.14108855]
 [-1.14197362 -0.64193818 -0.20656756  0.83016187  0.01675343]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [88]:
secuencia = np.random.randint(11, size=(1,20))
secuencia

array([[ 8,  7,  9,  9,  2,  2, 10,  6,  3,  9,  8, 10,  4,  4,  1,  3,
         5,  8,  6,  8]])

In [90]:
[-1 for element in secuencia if element >=3 or element <9]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.